language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=bionic
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    # Global build options and C++ flags
    - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
    # Misc
    - RUN_TESTS=true
    - COVERAGE=true

matrix:
  include:
    - os: linux
      dist: bionic
      python: 3.7
      sudo: true
      compiler: gcc-6
      addons:
       apt:
         packages: &precise_latest_boost_packages
           - gcc-6
           - g++-6
           - valgrind
           # Misc
           - python-yaml
           - lcov
           - doxygen
           - python3-pip
    
before_install:
    # Combine global build options with OS/compiler-dependent options
    - export CXX="g++-6"
    - export CC="gcc-6"
    - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
    - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    #- if [ "$CXX" = "clang++" ] && [ "$TRAVIS_OS_NAME" = "linux" ]; then export CXX="clang++-5.0" CC="clang-5.0"; fi
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - pyenv versions
    - python3 --version
    - sudo pip3 install codecov typing
    
    # Download and install recent cmake
    - |
      if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
        CMAKE_URL="https://cmake.org/files/v3.15/cmake-3.15.0-Linux-x86_64.tar.gz"
        mkdir -p ${DEPS_DIR}/cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      fi

script:
    ############################################################################
    # Build main and tests
    ############################################################################
     - mkdir -p build
     - cd build
     - cmake ${CMAKE_OPTIONS} -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON -DBUILD_DOC=ON -DBUILD_TESTING=ON ..
     - make
     - make doc 
     - make ccov-testuv3
     
after_success:
    - bash <(curl -s https://codecov.io/bash) -X coveragepy

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN #You will need to add your (ENCRYPTED if set in the .travis.yml) GH token as environment variable of your project
  keep-history: true
  on:
    branch: master
  local-dir: build/doc/doxygen/html